[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
numReplicas = 2
overlapSeconds = 30
drainingSeconds = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false

[env]
NODE_ENV = "production"
PORT = "3333"
